---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new-deployment
  labels:
    type: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      type: blue
  template:
    metadata:
      name: nginx-pod
      labels:
        type: blue
    spec:
     containers:
       - name: nginx
         image: nginx:1.25
...


