---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    author: intelliqit
    type: cicd
spec:
  containers:
    - name: myjekins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
...
